[project]
name = "fastmcp-v2"
version = "0.1.0"
description = "MCP Server written using fastmcp"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "fastmcp>=2.10.6"
]
