[project]
name = "mcp-python-sdk"
version = "0.1.0"
description = "MCP Server written using official MCP python SDK"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "mcp>=1.12.0",
]
